---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master

steps:
  - name: build
    image: rust:1.60
    commands:
      - cargo check
      - cargo clippy
      - cargo build --profile=bench
      - cargo test

  - name: benchmark
    image: rust:1.60
    commands:
      - cargo bench stark_bf

  - name: notify
    image: rust:1.60
    commands:
      - | curl --url 'smtp://mail.neptune.builders:25' --mail-from 'drone@mail.neptune.builders' --mail-rcpt 'simon@neptune.cash' -T <(echo -e "From: drone@mail.neptune.builders\nTo: simon@neptune.cash\nSubject: Curl Test\n\nHello")
