---
kind: pipeline
type: docker
name: default

steps:
  - name: Check
    image: rust:1.60
    commands:
      - cargo check
      - cargo check --tests

  - name: Build
    image: rust:1.60
    commands:
      - cargo build

  - name: Test
    image: rust:1.60
    commands:
      - cargo test

        #  - name: Benchmarks
        #    image: rust:1.60
        #    commands:
        #     - cargo bench stark_bf

trigger:
  branch:
    - master
