---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master

steps:
  - name: notifystart
    image: rust:1.60
    commands:
      - |
        sh -c 'curl --url "smtp://mail.neptune.builders:25" \
             --mail-from "drone@mail.neptune.builders" \
             --mail-rcpt "simon@neptune.cash" -T \
             <(echo -e "From: drone@mail.neptune.builders\nTo: simon@neptune.cash\nSubject: Curl Test\n\Build started..")'

  - name: build
    image: rust:1.60
    commands:
      - cargo check
      - cargo build --profile=bench
      - cargo test

  - name: benchmark
    image: rust:1.60
    commands:
      - cargo bench stark_bf

  - name: notifyend
    image: rust:1.60
    commands:
      - |
        sh -c 'curl --url "smtp://mail.neptune.builders:25" \
             --mail-from "drone@mail.neptune.builders" \
             --mail-rcpt "simon@neptune.cash" -T \
             <(echo -e "From: drone@mail.neptune.builders\nTo: simon@neptune.cash\nSubject: Curl Test\n\Build completed.")'
