# Please run `yamllint .drone.yml` after editing this file.
---
kind: pipeline
type: docker
name: default

# Run `rustup check` to see newest version and update here:
define: &latest_stable 'rust:1.61'

steps:
  - name: Check
    image: *latest_stable
    commands:
      - cargo check --all-targets

  - name: Clippy
    image: *latest_stable
    commands:
      - rustup component add clippy
      - cargo clippy --all-targets

  - name: Build
    image: *latest_stable
    commands:
      - RUSTFLAGS="-D warnings" cargo build --all-targets --profile=bench

  - name: Test
    image: *latest_stable
    commands:
      - cargo test --all-targets
      # Taget `doc` is not tested by `--all-targets` according to
      # [Target Selection]
      # (https://doc.rust-lang.org/cargo/commands/cargo-test.html#target-selection)
      - cargo test --doc

  - name: Bench
    image: *latest_stable
    commands:
      - cargo bench stark_bf

  - name: Telegram
    image: appleboy/drone-telegram
    secrets: [telegram_token, telegram_to]
    when:
      status: [success, failure]
    format: markdown
    # Reference:
    # https://github.com/appleboy/drone-telegram/blob/master/DOCS.md#parameter-reference
    message: >
      {{#success build.status}}
      ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.

      📝 Commit by {{commit.author}} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```

      🌐 {{ build.link }}
      {{else}}
      ❌ Build #{{build.number}} of `{{repo.name}}` failed.

      📝 Commit by {{commit.author}} on `{{commit.branch}}`:

      ```
      {{commit.message}}
      ```

      🌐 {{ build.link }}
      {{/success}}


branch:
  - master

...
# Please run `yamllint .drone.yml` after editing this file.
