---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master

steps:
  - name: build
    image: rust:1.61
    commands:
      - cargo check
      - rustup component add clippy
      - cargo clippy
      - cargo build --profile=bench
      - cargo test

  - name: benchmark
    image: rust:1.61
    commands:
      - cargo bench stark_bf
